### ISSUE TITLE
Разобраться наконец-то с чёртовым свайпоудалением в DraftsView, которое совсем без анимации

### ISSUE THREAD

**Issue by btimofeev** [vit1-irk/idec-mobile#14]

**Comment by btimofeev** [comment]
Если не ошибаюсь, то Lint выдает следующее сообщение как-раз по данному багу:

RecyclerView: RecyclerView Problems
../../src/main/java/vit01/idecmobile/DraftsView.java:236: Do not treat position as fixed; only use immediately and call holder.getAdapterPosition() to look it up later
 233         }
 234 
 235         @Override
 236         public void onBindViewHolder(ViewHolder holder, **int position**) {
 237             holder.position = position;
 238             File file = msglist.get(position);

../../src/main/java/vit01/idecmobile/EchoView.java:314: Do not treat position as fixed; only use immediately and call holder.getAdapterPosition() to look it up later
 311 
 312         // Replace the contents of a view (invoked by the layout manager)
 313         @Override
 314         public void onBindViewHolder(ViewHolder holder, **int position**) {
 315             // - get element from your dataset at this position
 316             // - replace the contents of the view with that element

Priority: 8 / 10
Category: Correctness
Severity: Error
Explanation: RecyclerView Problems.
RecyclerView will not call onBindViewHolder again when the position of the item changes in the data set unless the item itself is invalidated or the new position cannot be determined.

For this reason, you should only use the position parameter while acquiring the related data item inside this method, and should not keep a copy of it.

If you need the position of an item later on (e.g. in a click listener), use getAdapterPosition() which will have the updated adapter position.

**Comment by vit1-irk** [comment]
Попробовал полностью избавиться от holder.position и вообще от использования этого значения, но ничего не изменилось.
