### ISSUE TITLE
Не отображается количество непрочитанных сообщений

### ISSUE THREAD

**Issue by btimofeev** [vit1-irk/idec-mobile#17]
В некоторых случаях, почему то, не отображается количество непрочитанных сообщений. Пример на скриншоте: http://ipic.su/img/img7/fs/Screenshot_20161006-192841.1475771553.png

**Comment by btimofeev** [comment]
Число исчезает при прокрутке списка. https://www.dropbox.com/s/ke5st0gx01geug8/Telecine_2016-10-07-09-53-47.mp4

**Comment by vit1-irk** [comment]
Починил с помощью принудительного setVisible(View.VISIBLE)
