### ISSUE TITLE
Цвет статусбара при загрузке приложения

### ISSUE THREAD

**Issue by btimofeev** [vit1-irk/idec-mobile#20]
Если выбрать любую кастомную тему, то при запуске приложения на секунду цвет статусбара окрашивается фиолетовым, фон активити белым, а потом уже устанавливается выбранная тема. Это подгружается тема из AndroidManifest. 

Если убрать параметр темы в манифесте, то первой загружается какая-то стандартная темная тема. Думаю нам надо попробовать найти способ загрузить свою выбранную тему раньше.

**Comment by vit1-irk** [comment]
Я понял, почему это происходит.
Всё из-за строчки https://github.com/vit1-irk/idec-mobile/blob/276886a2adaae7f4e282f87ee11fca0be045ebd2/app/src/main/java/vit01/idecmobile/MainActivity.java#L70
Я ещё назвал её опечаткой. Если это убрать, то статусбар сразу окрасится в нужный цвет.

Правда, теперь появился один минус. Экран приложения запускается не сразу после нажатия на иконку, а после задержки.
Задержка из-за чтения конфига возникает, конечно же.
