### ISSUE TITLE
Перекрашенный пиксель в левом верхнем углу картинки NavigationDrawer'а 

### ISSUE THREAD

**Issue by btimofeev** [vit1-irk/idec-mobile#21]
В левом верхнем углу картинки NavigationDrawer'а откуда-то появился перекрашенный пиксель. Причём он перекрашивается в зависимости от цвета фона круглой иконки станции.

**Comment by vit1-irk** [comment]
Цвет фона генерируется вот здесь, как ты уже заметил, наверное.

https://github.com/vit1-irk/idec-mobile/blob/master/app/src/main/java/vit01/idecmobile/MainActivity.java#L351

Может быть, что-нибудь из NavDrawer'а зависит от состояния одного из используемых классов (например, Color).
