### ISSUE TITLE
Цвет чекбокса в меню тулбара

### ISSUE THREAD

**Issue by btimofeev** [vit1-irk/idec-mobile#22]
В темных темах в меню тулбара чекбокс (например "Вид: только непрочитанные [ ]") в неактивном состоянии рисуется черным цветом на темном же фоне.

**Comment by btimofeev** [comment]
Похоже эта проблема связана с проблемой #19. 

Здесь так же будет все хорошо, если убрать из строки https://github.com/vit1-irk/idec-mobile/blob/master/app/src/main/res/values/styles.xml#L140 атрибут Light, но тогда в светлых темах будет плохое отображение.

**Comment by vit1-irk** [comment]
Я разобрался с этой проблемой. В сегодняшнем коммите покажу.
