### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by btimofeev** [vit1-irk/idec-mobile#25]
На сайте проекта GNU сказано, что добавления одного только файла с лицензией не достаточно https://www.gnu.org/licenses/gpl-faq.html#LicenseCopyOnly

Необходимо в каждый файл с исходником добавить заголовок с информацией о лицензии, с копирайтом каждого человека работавшего над этим файлом и годом в котором каждый человек  делал изменения.  Вот руководство как это всё делать https://www.gnu.org/licenses/gpl-howto.html

И ссылку в корне LICENSE.html лучше заменить на текстовый файл COPYING (по ссылке выше это тоже написано).

**Comment by vit1-irk** [comment]
Добавил шаблон ко всем java-исходникам и всунул COPYING
